[2024-09-10T02:23:26.772+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-10T02:23:26.776+0800] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: puzzle-pieces-picker_elt.download_puzzle-pieces-picker manual__2024-09-09T18:23:19.376310+00:00 [queued]>
[2024-09-10T02:23:26.778+0800] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: puzzle-pieces-picker_elt.download_puzzle-pieces-picker manual__2024-09-09T18:23:19.376310+00:00 [queued]>
[2024-09-10T02:23:26.778+0800] {taskinstance.py:2865} INFO - Starting attempt 1 of 4
[2024-09-10T02:23:26.782+0800] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): download_puzzle-pieces-picker> on 2024-09-09 18:23:19.376310+00:00
[2024-09-10T02:23:26.790+0800] {logging_mixin.py:190} WARNING - /Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=71821) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-10T02:23:26.789+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'puzzle-pieces-picker_elt', 'download_puzzle-pieces-picker', 'manual__2024-09-09T18:23:19.376310+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/var/folders/3n/sh024_795c590k086c59jsw00000gn/T/tmpiusfdfpd']
[2024-09-10T02:23:26.790+0800] {standard_task_runner.py:72} INFO - Started process 71824 to run task
[2024-09-10T02:23:26.790+0800] {standard_task_runner.py:105} INFO - Job 44: Subtask download_puzzle-pieces-picker
[2024-09-10T02:23:26.805+0800] {task_command.py:467} INFO - Running <TaskInstance: puzzle-pieces-picker_elt.download_puzzle-pieces-picker manual__2024-09-09T18:23:19.376310+00:00 [running]> on host chens-macbook-pro.local
[2024-09-10T02:23:26.830+0800] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='puzzle-pieces-picker_elt' AIRFLOW_CTX_TASK_ID='download_puzzle-pieces-picker' AIRFLOW_CTX_EXECUTION_DATE='2024-09-09T18:23:19.376310+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-09T18:23:19.376310+00:00'
[2024-09-10T02:23:26.831+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-10T02:23:26.831+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-10T02:23:26.831+0800] {logging_mixin.py:190} INFO - Current task name:download_puzzle-pieces-picker state:running start_date:2024-09-09 18:23:26.776623+00:00
[2024-09-10T02:23:26.831+0800] {logging_mixin.py:190} INFO - Dag name:puzzle-pieces-picker_elt and current dag run status:running
[2024-09-10T02:23:26.832+0800] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-10T02:23:26.932+0800] {s3.py:36} ERROR - Error checking s3://if-letters-home-could-sing/data/puzzle-pieces-picker.zip: An error occurred (403) when calling the HeadObject operation: Forbidden
[2024-09-10T02:23:26.935+0800] {baseoperator.py:405} WARNING - DownloadOperator.execute cannot be called outside TaskInstance!
[2024-09-10T02:23:26.982+0800] {logging_mixin.py:190} INFO - Error updating job state: An error occurred (UnrecognizedClientException) when calling the UpdateItem operation: The security token included in the request is invalid.
[2024-09-10T02:23:26.998+0800] {s3.py:36} ERROR - Error checking s3://if-letters-home-could-sing/data/puzzle-pieces-picker.zip: An error occurred (403) when calling the HeadObject operation: Forbidden
[2024-09-10T02:29:08.363+0800] {s3.py:17} ERROR - Error uploading to s3://if-letters-home-could-sing/data/puzzle-pieces-picker.zip: An error occurred (InvalidAccessKeyId) when calling the CreateMultipartUpload operation: The AWS Access Key Id you provided does not exist in our records.
[2024-09-10T02:29:08.376+0800] {s3.py:47} ERROR - Error getting info for s3://if-letters-home-could-sing/data/puzzle-pieces-picker.zip: An error occurred (403) when calling the HeadObject operation: Forbidden
[2024-09-10T02:29:08.376+0800] {download.py:43} INFO - Downloaded and uploaded: data/puzzle-pieces-picker.zip
[2024-09-10T02:29:08.436+0800] {logging_mixin.py:190} INFO - Error updating job state: An error occurred (UnrecognizedClientException) when calling the UpdateItem operation: The security token included in the request is invalid.
[2024-09-10T02:29:08.436+0800] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/code/erniesg/if-letters-home-could-sing/pipeline/dags/elt.py", line 51, in process_download
    result = download_op.execute(kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/code/erniesg/if-letters-home-could-sing/pipeline/operators/download.py", line 44, in execute
    self.log.info(f"Size: {file_info['ContentLength']}, Type: {file_info['ContentType']}")
                           ~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-09-10T02:29:08.515+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-10T02:29:08.515+0800] {logging_mixin.py:190} INFO - Task start:2024-09-09 18:23:26.776623+00:00 end:2024-09-09 18:29:08.515283+00:00 duration:341.73866
[2024-09-10T02:29:08.515+0800] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): download_puzzle-pieces-picker> dag:<DAG: puzzle-pieces-picker_elt> dagrun:<DagRun puzzle-pieces-picker_elt @ 2024-09-09 18:23:19.376310+00:00: manual__2024-09-09T18:23:19.376310+00:00, state:running, queued_at: 2024-09-09 18:23:19.382902+00:00. externally triggered: True>
[2024-09-10T02:29:08.516+0800] {logging_mixin.py:190} INFO - Failure caused by 'NoneType' object is not subscriptable
[2024-09-10T02:29:08.516+0800] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=puzzle-pieces-picker_elt, task_id=download_puzzle-pieces-picker, run_id=manual__2024-09-09T18:23:19.376310+00:00, execution_date=20240909T182319, start_date=20240909T182326, end_date=20240909T182908
[2024-09-10T02:29:08.520+0800] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-10T02:29:08.520+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 44 for task download_puzzle-pieces-picker ('NoneType' object is not subscriptable; 71824)
Traceback (most recent call last):
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/code/erniesg/if-letters-home-could-sing/pipeline/dags/elt.py", line 51, in process_download
    result = download_op.execute(kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/.pyenv/versions/3.12.5/envs/letters_home/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erniesg/code/erniesg/if-letters-home-could-sing/pipeline/operators/download.py", line 44, in execute
    self.log.info(f"Size: {file_info['ContentLength']}, Type: {file_info['ContentType']}")
                           ~~~~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[2024-09-10T02:29:08.553+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-10T02:29:08.560+0800] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-10T02:29:08.561+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
